# Mod info
mod_id=ae2rsbridge
mod_name=AE2 RS Bridge
mod_version=1.0.0
mod_group_id=com.ae2rsbridge
mod_authors=Kalloer1
mod_description=Bidirectional storage bridge between Applied Energistics 2 and Refined Storage

# Minecraft / Forge
minecraft_version=1.20.1
forge_version=47.3.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
